---

- name: Ensure Foreman user group exists
  ansible.builtin.group:
    name: '{{ foreman_system_user.name }}'
    gid: '{{ foreman_system_user.gid }}'
    state: '{{ foreman_system_user.state | default("present") }}'
  failed_when: false
  tags:
    - always

- name: Ensure Foreman user exists
  ansible.builtin.user:
    name: '{{ foreman_system_user.name }}'
    uid: '{{ foreman_system_user.uid }}'
    groups:
      - '{{ foreman_system_user.name }}'
    create_home: '{{ foreman_user_group.state | default("present") == "present" }}'
    home: '{{ foreman_system_user.home_dir }}'
    state: '{{ foreman_user_group.state | default("present") }}'
  failed_when: false
  tags:
    - always

- name: Process User Directory
  ansible.builtin.include_tasks:
    file: foreman_user_directories.yml
  loop: '{{ foreman_user_group.directories | default([]) }}'
  loop_control:
    loop_var: foreman_user_directory
    label: '{{ foreman_system_user.name }}'
  tags:
    - always
